### ISSUE TITLE
 xp-for-developers-essentials branch is not in sync with your training

### ISSUE THREAD

**Issue by briankitt** [Kentico/xperience-training-13#111]
### Brief bug description
 xp-for-developers-essentials branch is not in sync with your training

What went wrong?
It is impossible for a NOOB to go through the training.  Either the training or the  xp-for-developers-essentials branch is out of alignment

### Repro steps
Go through the developer training, step by step on a computer that has never had Kentico

First problem: 'Get the Code' step has you use the same branch, regardless of the route you are going to take.  I believe the branch for 'route 2' is wrong.
Second problem:  At no point do you tell the viewer to 'compile the code'.  The installer will not run until the code is compiled.
Third problem: At no point do you say 7Zip is required.  The code will not compile without 7Zip, and it's not in the 'required software' list
Fourth problem:  Cannot get through the installer.  The installer keeps failing, but gives no indication what the problem is.  The log gives no indication of what the problem is. 
The database is never created.  So my guess, is that there is something wrong in the step with the database.

At this point, your instructions are useless.  If I have this many problems during the 'get code', I'm not wasting my time going further.

### Expected behavior

I would expect a 'step by step' 'how to' wouldn't fail on 'install Kentico' step.

**Comment by JanLenoch** [comment]
Hello @briankitt ,

Thank you for your interest in Kentico Xperience! Right up front, please let me reiterate that Kentico is a mature DXP platform that requires the developer to have at least some technical background and be proficient in ASP.NET Core MVC. It is sadly beyond our possibilities to train absolute beginners.

However, I'll do my best to bring you back on track.

First, the "Get the code" chapter is correct. The difference between the two routes lies in the following:

* While in the "Coding along the course" route, "_the only thing you will use from the branch will be the XML files that you'll use to restore the database objects into your MS SQL Server database_" (citing the course).
* In the "Inspecting the result ..." route, you utilize the whole repository.

Next, you don't need to compile anything to run the Kentico Xperience installer. It lacks sense. There is no code to compile. If you chose the "coding along" route, you need to first install default solution files together with a blank database using the installer. Then, copy the XML files from the cloned repository, and run the ContinuousIntegration.exe utility from your installed folder (i.e., not from the cloned one). After some additional configuration steps outlined in the course, you'll be able to start developing (and compiling).

As for 7Zip, I'm afraid you misunderstood one of the instructions. To go through the course, no ZIP utility is required. Maybe you misunderstood an instruction telling you to clone the repository instead of downloading it as a ZIP file. But as you can see, the instruction tells you _not_ to download it as a ZIP file. There is definitely no need to use any archiving utility anywhere in the course. I'd love to learn why you concluded the need to use 7Zip.

If your installer is failing, there is a way to learn why that is. At the end of the failed installation process, the installer always gives you the option to view a detailed log of what has been done. You can use that option, send us the log, and we'll see what needs to be changed to finish the installation.

If your database is never created, then it quite logically can be caused by the fact that the installer couldn't proceed to create the database. Viewing the installer log helps in such cases.

I hope that helps. Please let me know what you found out. I'll be happy to help more.

Jan

**Comment by briankitt** [comment]
I've been working in .NET for 21 years now.  So I'm not a NOOB to .NET,
only to Kentico.  Sorry about the confusion on that.
Your installer wouldn't go past the directory selection, until I compiled
the code.
When I compiled it, it barked at me that I needed 7zip installed, so I did
that.
Once I got a clean compile, the installer moved forward, then quit,
throwing an error.
I went line by line through the log, and found no reason for an error.

**Comment by JanLenoch** [comment]
Hello @briankitt ,

Thanks for your reply. As I said, we can help you only if you send us the installation log. Assuming from your repeated mention of the compilation before installation, we may not be on the same page. Please let me explain again that the installer does not need anything to be compiled by you upfront. As the course clearly instructs, you just clone the XML files from GH to a temporary location, install a blank solution together with a blank database, do other configuration steps, and then you start developing and compiling. Not the other way around.

I asked our colleagues from the Support department for assistance with your issue with the installer. They're more skilled with the installer, so they'll be able to help you in detail. They will reach out to you by email. Please have your detailed (i.e., specific) list of repro steps along with the installation log prepared.

I hope you'll be able to continue with your efforts again soon. If you then encounter any other issue with the Xperience 13 for developers course, do not hesitate to get in touch with me again.

Jan
