### ISSUE TITLE
README instruction for Xperience_13_Refresh1 

### ISSUE THREAD

**Issue by mustafa-noman** [Kentico/xperience-training-13#82]
the README file step does not work for Xperience_13_Refresh1 installation. can you check & update the README file / repo for Xperience_13_Refresh1 ?

**Comment by JanLenoch** [comment]
Hello @mustafa-noman , most probably it isn't caused by Refresh 1 but the fact that the readme contains just a high-level list of instructions. The full instructions can be found in the course. I'll most probably remove the high-level steps from the readme entirely, to avoid further confusion.

I was wondering, did you follow the full set of preparation steps in the "Xperience basics, development prerequisites" page in the course? Or just those in the readme?

Thank you.

**Comment by mustafa-noman** [comment]
hi @JanLenoch, yes follow  just those in the readme & thought I will be able to run the site, I try 2/3 time to make it work but couldn't 
thanks for the clarification

**Comment by JanLenoch** [comment]
Great you've been able to work through that. If you hit any other obstacle, just let me know and I'll gladly help. Enjoy your learning!
