### ISSUE TITLE
Examples of Insert methods to programmatically add Page Types/Templates/Fields/Content, etc.

### ISSUE THREAD

**Issue by flyinmryan** [Kentico/xperience-training-13#89]
https://devnet.kentico.com/docs/13_0/api/html/T_CMS_DocumentEngine_TreeNode.htm
Or BaseInfo.Insert.   The documentation lists the methods, but demonstrates none.  I thought this was supposed to be a fully implemented solution.  Thanks

**Comment by flyinmryan** [comment]
Without these examples I don't believe the repo is truly a fully implemented solution as is stated in the paid Xperience training, but I will ask on stackoverflow or keep looking elsewhere.

**Comment by JanLenoch** [comment]
Hello @flyinmryan ,

I'm wondering why you think you need to programmatically add page types. Creation of page types, their fields, or page templates, is exclusively an act of a human invention. Unless you have a very specific business requirements you'd rather want to keep control over the design process. Such automation makes sense in a narrow set of situations, e.g. when a large e-commerce site needs to regularly synchronize its product definitions with an internal ERP system. However, such scenarios really don't fall into the scope of an essential Kentico Xperience course.

I'd like to better understand your remark. Could you elaborate more on it? Thanks.

**Comment by flyinmryan** [comment]
Hi @JanLenoch, sure I can elaborate a bit.  It's basically repetitive tasks, minor UI headaches that begin to be an annoyance, and the amount of time I wait and watch for the loading/saving icon to drop off the screen for each item.  I am tasked with creating about 20 components with an average of about 10 fields each, and I will need to eventually create about 100 pages.

Creating a new Page Type:  Fill in three text inputs.  On a split screen I can't see a "next" or "continue" or "save" button because the page isn't responsive, so I have to grab the mouse and drag the bar to reveal the button.  Then drag back for the next screen.  Next select features, and there's no button.  Next DB table setup, no button.  

Next enter Fields:  Click New Field, click into the Field name input to enter name.  For a new user there is no visual cue to hint that there are many more properties to enter below what fits neatly in the window, look for the button...not there.  Tabbing thru the inputs eventually reveals more inputs.  Look for button, but can't scroll over.  Have to expand browser width to reveal Next button.

Next is selecting Parent types.  Many page types are in the table, but they all have a empty checkbox next to them.  If I check the boxes of the pages I want and click "Next" does that save them only as the Parents types?  No, because all the items with empty check boxes are in fact "selected" as Parent types by default.  So I have to check the boxes of what I DO NOT want as Parent and then click the "Remove selected" button, even though the directions say "Please select page types under which this page template can be placed."  It should say, "Remove any page types you do NOT want as Parent and click Remove selected.  Any remaining types will be added as Parent."

Next, if I want to view or add Fields to an existing Page Type from the Page Type CMS page, I can't just click on a row to view what's there, I have to click the pencil icon which puts it into a live edit stage where mistakes can be made and will take effect as soon as work is saved even if it's just a habit of constantly saving progress finished or not.

Click "Fields" -> "New Field" -> no auto cursor to first input, click into Field name and start entering fields.  If they are entered out of order, the field nodes can be moved one space at a time with one click each time, no sorting via drag and drop.

Enter fields one by one...no scroll bar to view off screen?  Nope, the save button is now in the upper left side of the page.  Click....Saving.....Repeat.

I can do that a few hundred times, or write a simple script to parse the business plan or even a specific development plan, extract the pages/components/fields/templates, and programmatically create everything.  Debug if needed, delete is needed, or relax if it worked.

I hope that helps to understand why I would want to automate the very repetitive nature of the tasks.

Thanks,
Mike

**Comment by flyinmryan** [comment]
Found this helpful page:  https://docs.xperience.io/api10/content-management/pages#Pages-Pagemanagement

**Comment by JanLenoch** [comment]
Hi @flyinmryan ,

Thanks for the clarification. I'd split my answer into several parts.

First, I personally agree with most of your comments about the UX in the process of creating new page types. And I've got great news for you: We're currently working on the UI of the administrative section for the next major version. I forwarded your comments to our UX guys and I think there is quite a big chance that the creation of page types will meet our expectations.

Second, UX mishaps shall not push us to start telling our customers to create page types programmatically. A set of scripts or an API would definitely bring value and I'll let our product managers know about that. But these automated methods shall not replace the UI method of adding page types.

Third, the Essentials module is focused on creating a basic web application in standard ways, with some additional robustness and testability. If the product gets features to create page types in an automated ways, I'd definitely add a chapter about that into our courses. However, I'm not sure it would be a good idea to start the Essentials course with such a method. The reason is that the wizard is structured and the API wouldn't be. By going through the wizard, one learns which options apply to which parts of the creation process. In the API, you'd have to study it all at once to understand to which steps is a particular option applicable and to which it isn't.

May I ask you, what page types did you create during the Essentials course? Because in v13, we switched to using our Continuous Integration feature to automatically populate the whole database for you, including all page types and the respective pages.

I hope I managed to explain the situation to you. If there's anything else you think I could help you with, feel free to let me know. 

Jan
